spring:
  jpa:
    generate-ddl: 'true'
    database: MYSQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: MYSQL
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3306/diploma
    password: password
server:
  port: '8080'
